
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author olimp
 */
public class NewJFrame extends javax.swing.JFrame {

    private int con;
    private int x;
    private int o;
    private String resul;
    
    /**
     * Creates new form NewJFrame
     */
   
    public NewJFrame() {
        initComponents();
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
     x=0;
     o=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        Iniciar = new javax.swing.JButton();
        nome = new javax.swing.JLabel();
        cred = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        Iniciar.setBackground(new java.awt.Color(0, 255, 102));
        Iniciar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        Iniciar.setText("Iniciar Jogo");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        nome.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        nome.setText("Velha Maluca");

        cred.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        cred.setText("LEONAM S. RABELO      TI431");
        cred.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel1.setText("Jogador O:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setText("Jogador X:");

        jTextField2.setText("0");

        jLabel3.setText("PLACAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(41, 51, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(0, 5, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 255, 102));
        jMenuBar1.setForeground(new java.awt.Color(51, 255, 51));

        jMenu1.setBackground(new java.awt.Color(153, 255, 153));
        jMenu1.setText("Opções");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Ajuda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sobre");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Limpar placar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Sair do jogo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cred))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(174, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cred))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        con++;
        if(con==1 || con==3 || con==5 || con==7 || con==9){
        b3.setText("X");
        }
                if(con==2 || con==4 || con==6 || con==8){
        b3.setText("O");
        }
                
        b3.setEnabled(false);
        if(((b1.getText()).equals("X")) && ((b2.getText()).equals("X")) &&
            ((b3.getText()).equals("X"))){
        x++;
        resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
        Iniciar.setEnabled(true);  
        }
        
   if(((b1.getText()).equals("O")) && ((b2.getText()).equals("O")) &&
          ((b3.getText()).equals("O"))){
        o++;
        resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
   Iniciar.setEnabled(true);       
   }
   
   	if(b3.getText().equals("X") && b6.getText().equals("X") && b9.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
      Iniciar.setEnabled(true);  
        }
	
	if(b3.getText().equals("O") && b6.getText().equals("O") && b9.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
        Iniciar.setEnabled(true);  
        }
        
      if(b3.getText().equals("X") && b5.getText().equals("X") && b7.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
      Iniciar.setEnabled(true);  
      }
	
     if(b3.getText().equals("O") && b5.getText().equals("O") && b7.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
     Iniciar.setEnabled(true);   
     }
     if(con==9 && !"vence".equals(resul)){
        JOptionPane.showMessageDialog(null, "JOGO EMPATADO!");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
        Iniciar.setEnabled(true); 
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        con=0;
    Iniciar.setEnabled(false);
     b1.setEnabled(true);
     b2.setEnabled(true);
     b3.setEnabled(true);
     b4.setEnabled(true);
     b5.setEnabled(true);
     b6.setEnabled(true);
     b7.setEnabled(true);
     b8.setEnabled(true);
     b9.setEnabled(true);

    }//GEN-LAST:event_IniciarActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        con++;
        if(con==1 || con==3 || con==5 || con==7 || con==9){
        b9.setText("X");
        }
                if(con==2 || con==4 || con==6 || con==8){
        b9.setText("O");
        }
        b9.setEnabled(false);
      
	if(b7.getText().equals("X") && b8.getText().equals("X") && b9.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
        Iniciar.setEnabled(true);  
        }
	
	if(b7.getText().equals("O") && b8.getText().equals("O") && b9.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
        Iniciar.setEnabled(true);  
        }
        
	if(b3.getText().equals("X") && b6.getText().equals("X") && b9.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
        Iniciar.setEnabled(true);  
        }
	
	if(b3.getText().equals("O") && b6.getText().equals("O") && b9.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
        Iniciar.setEnabled(true);  
        }
        
    if(b1.getText().equals("X") && b5.getText().equals("X") && b9.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
    Iniciar.setEnabled(true);  
    }
	
	if(b1.getText().equals("O") && b5.getText().equals("O") && b9.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
        Iniciar.setEnabled(true);  
        }
        if(con==9 && !"vence".equals(resul)){
        JOptionPane.showMessageDialog(null, "JOGO EMPATADO!");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
        Iniciar.setEnabled(true); 
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        con++;
        if(con==1 || con==3 || con==5 || con==7 || con==9){
        b8.setText("X");
        }
                if(con==2 || con==4 || con==6 || con==8){
        b8.setText("O");
        }
        b8.setEnabled(false);
        
	if(b7.getText().equals("X") && b8.getText().equals("X") && b9.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
        Iniciar.setEnabled(true);  
        }
	
    if(b7.getText().equals("O") && b8.getText().equals("O") && b9.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
    Iniciar.setEnabled(true);    
    }

    if(b2.getText().equals("X") && b5.getText().equals("X") && b8.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b9.setEnabled(false);
    Iniciar.setEnabled(true);  
    }
	
    if(b2.getText().equals("O") && b5.getText().equals("O") && b8.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b9.setEnabled(false);
    Iniciar.setEnabled(true);  
    }
    if(con==9 && !"vence".equals(resul)){
        JOptionPane.showMessageDialog(null, "JOGO EMPATADO!");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
        Iniciar.setEnabled(true); 
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        con++;
        if(con==1 || con==3 || con==5 || con==7 || con==9){
        b4.setText("X");
        }
                if(con==2 || con==4 || con==6 || con==8){
        b4.setText("O");
        }
        b4.setEnabled(false);
     
     if(b4.getText().equals("X") && b5.getText().equals("X") && b6.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
     Iniciar.setEnabled(true);    
     }
	
    if(b4.getText().equals("O") && b5.getText().equals("O") && b6.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
    Iniciar.setEnabled(true);  
    }
    
      if(b1.getText().equals("X") && b4.getText().equals("X") 
                        && b7.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b2.setEnabled(false);
     b3.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
      Iniciar.setEnabled(true);  
      }
	
    if(b1.getText().equals("O") && b4.getText().equals("O") && b7.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b2.setEnabled(false);
     b3.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
    Iniciar.setEnabled(true);   
    }
    if(con==9 && !"vence".equals(resul)){
        JOptionPane.showMessageDialog(null, "JOGO EMPATADO!");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
        Iniciar.setEnabled(true); 
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        con++;
        if(con==1 || con==3 || con==5 || con==7 || con==9){
        b7.setText("X");
        }
                if(con==2 || con==4 || con==6 || con==8){
        b7.setText("O");
        }
        b7.setEnabled(false);
        
	if(b7.getText().equals("X") && b8.getText().equals("X") && b9.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
        Iniciar.setEnabled(true);  
        }
	
    if(b7.getText().equals("O") && b8.getText().equals("O") && b9.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     Iniciar.setEnabled(true);  
    }
 if(b1.getText().equals("X") && b4.getText().equals("X") && b7.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b2.setEnabled(false);
     b3.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
     Iniciar.setEnabled(true);    
 }
	
    if(b1.getText().equals("O") && b4.getText().equals("O") && b7.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b2.setEnabled(false);
     b3.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
    Iniciar.setEnabled(true);    
    }
    
    if(b3.getText().equals("X") && b5.getText().equals("X") && b7.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
    Iniciar.setEnabled(true);  
    }

    if(b3.getText().equals("O") && b5.getText().equals("O") && b7.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
    Iniciar.setEnabled(true);  
    }
    if(con==9 && !"vence".equals(resul)){
        JOptionPane.showMessageDialog(null, "JOGO EMPATADO!");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
        Iniciar.setEnabled(true); 
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        int confirm;
        confirm = JOptionPane.showConfirmDialog(null, "Deseja realmente encerrar?");
        if(confirm == JOptionPane.YES_OPTION){
        System.exit(0);
       }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        con++;
        if(con==1 || con==3 || con==5 || con==7 || con==9){
        b1.setText("X");
        }
                if(con==2 || con==4 || con==6 || con==8){
        b1.setText("O");
        }
        b1.setEnabled(false);
      
      if(((b1.getText()).equals("X")) && ((b2.getText()).equals("X")) &&
          ((b3.getText()).equals("X"))){
        x++;
        resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
      Iniciar.setEnabled(true);  
      }
     if(((b1.getText()).equals("O")) && ((b2.getText()).equals("O")) &&
          ((b3.getText()).equals("O"))){
        o++;
        resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
     Iniciar.setEnabled(true);     
     }
     	if(b1.getText().equals("X") && b4.getText().equals("X") && b7.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b2.setEnabled(false);
     b3.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
       Iniciar.setEnabled(true);  
        }
	
	if(b1.getText().equals("O") && b4.getText().equals("O") && b7.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b2.setEnabled(false);
     b3.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
        Iniciar.setEnabled(true);  
        }
        
	if(b1.getText().equals("X") && b5.getText().equals("X") && b9.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
        Iniciar.setEnabled(true);  
        }
	
	if(b1.getText().equals("O") && b5.getText().equals("O") && b9.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
        Iniciar.setEnabled(true);  
        }
        if(con==9 && !"vence".equals(resul)){
        JOptionPane.showMessageDialog(null, "JOGO EMPATADO!");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
        Iniciar.setEnabled(true); 
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
           con++;
        if(con==1 || con==3 || con==5 || con==7 || con==9){
        b2.setText("X");
        }
                if(con==2 || con==4 || con==6 || con==8){
        b2.setText("O");
    }
                b2.setEnabled(false);
      //fim de jogo/vencedor
        if(((b1.getText()).equals("X")) && ((b2.getText()).equals("X")) &&
            ((b3.getText()).equals("X"))){
        x++;
        resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
        Iniciar.setEnabled(true);  
        }
        
    if(((b1.getText()).equals("O")) && ((b2.getText()).equals("O")) &&
          ((b3.getText()).equals("O"))){
        o++;
        resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
    Iniciar.setEnabled(true);      
    }
    if(b2.getText().equals("X") && b5.getText().equals("X") && b8.getText().equals("X")){
	 x++;
         resul="vece";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b9.setEnabled(false);
    Iniciar.setEnabled(true);  
    }
	
        if(b2.getText().equals("O") && b5.getText().equals("O") && b8.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b9.setEnabled(false);
        Iniciar.setEnabled(true);  
        }
        if(con==9 && !"vence".equals(resul)){
        JOptionPane.showMessageDialog(null, "JOGO EMPATADO!");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
        Iniciar.setEnabled(true); 
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        con++;
        if(con==1 || con==3 || con==5 || con==7 || con==9){
        b5.setText("X");
        }
                if(con==2 || con==4 || con==6 || con==8){
        b5.setText("O");
        }
        b5.setEnabled(false);
   if(b4.getText().equals("X") && b5.getText().equals("X") && b6.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
   Iniciar.setEnabled(true);   
   }
   
   if(b4.getText().equals("O") && b5.getText().equals("O") && b6.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
   Iniciar.setEnabled(true);     
   }
    
   if(b2.getText().equals("X") && b5.getText().equals("X") && b8.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b9.setEnabled(false);
   Iniciar.setEnabled(true);  
   }
	
   if(b2.getText().equals("O") && b5.getText().equals("O") && b8.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b9.setEnabled(false);
   Iniciar.setEnabled(true);       
   }
   
    if(b1.getText().equals("X") && b5.getText().equals("X") && b9.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
    Iniciar.setEnabled(true);     
    }
	
    if(b1.getText().equals("O") && b5.getText().equals("O") && b9.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
    Iniciar.setEnabled(true);      
    }
    
    if(b3.getText().equals("X") && b5.getText().equals("X") && b7.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
    Iniciar.setEnabled(true);     
    }
	
    if(b3.getText().equals("O") && b5.getText().equals("O") && b7.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b4.setEnabled(false);
     b6.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
    Iniciar.setEnabled(true);    
    }
    if(con==9 && !"vence".equals(resul)){
        JOptionPane.showMessageDialog(null, "JOGO EMPATADO!");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
        Iniciar.setEnabled(true); 
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        con++;
        if(con==1 || con==3 || con==5 || con==7 || con==9){
        b6.setText("X");
        }
                if(con==2 || con==4 || con==6 || con==8){
        b6.setText("O");
        }
        b6.setEnabled(false);
     if(b4.getText().equals("X") && b5.getText().equals("X") && 
                        b6.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
     Iniciar.setEnabled(true);  
     }
	
    if(b4.getText().equals("O") && b5.getText().equals("O") && 
                b6.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
    Iniciar.setEnabled(true);   
    }
    
    if(b3.getText().equals("X") && b6.getText().equals("X") && b9.getText().equals("X")){
	 x++;
         resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador X é o vencedor");
        jTextField1.setText("" + x);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
    Iniciar.setEnabled(true);  
    }
	
    if(b3.getText().equals("O") && b6.getText().equals("O") && b9.getText().equals("O")){
		o++;
                resul="vence";
        JOptionPane.showMessageDialog(null, "Jogador O é o vencedor");
        jTextField2.setText("" + o);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
    Iniciar.setEnabled(true);  
    }
    if(con==9 && !"vence".equals(resul)){
        JOptionPane.showMessageDialog(null, "JOGO EMPATADO!");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
     b1.setEnabled(false);
     b2.setEnabled(false);
     b3.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
     b8.setEnabled(false);
     b9.setEnabled(false);
        Iniciar.setEnabled(true); 
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    new Ajuda().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
new Sobre().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    jTextField1.setText("0");
    jTextField2.setText("0");
    x=0;
    o=0;
    Iniciar.setEnabled(true);
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel cred;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel nome;
    // End of variables declaration//GEN-END:variables
}
